In [1]:
dp1 = {'partno': 100, 'maxtemp': 35, 'mintemp': 35, 'maxvibration': 12, 'asperity': 0.32}
dp2 = {'partno': 101, 'maxtemp': 46, 'mintemp': 35, 'maxvibration': 21, 'asperity': 0.34}
dp3 = {'partno': 130, 'maxtemp': 56, 'mintemp': 46, 'maxvibration': 3412, 'asperity': 12.42}
dp4 = {'partno': 131, 'maxtemp': 58, 'mintemp': 48, 'maxvibration': 3542, 'asperity': 13.43}

In [2]:
def predict(dp):
    if dp['maxvibration']> 100:
        return 13
    else:
        return 0.33

In [3]:
predict(dp1)

0.33

In [10]:
predict(dp2)

0.33

In [4]:
predict(dp3)

13

In [5]:
predict(dp4)

13

In [6]:
w1 = 0.30
w2 = 0
w3 = 0
w4 = 13/3412.0

def mlpredict(dp):
    return w1+w2*dp['maxtemp']+w3*dp['mintemp']+w4*dp['maxvibration']

In [7]:
mlpredict(dp4)

13.795310668229778

In [8]:
dp1 = {'partno': 100, 'maxtemp': 35, 'mintemp': 35, 'maxvibration': 12, 'broken': 0}
dp2 = {'partno': 101, 'maxtemp': 46, 'mintemp': 35, 'maxvibration': 21, 'broken': 0}
dp3 = {'partno': 130, 'maxtemp': 56, 'mintemp': 46, 'maxvibration': 3412, 'broken': 1}
dp4 = {'partno': 131, 'maxtemp': 58, 'mintemp': 48, 'maxvibration': 3542, 'broken': 1}

In [10]:
def predict(dp):
    if dp['maxvibration']> 100:
        return 1
    else:
        return 0

In [11]:
predict(dp1)

0

In [105]:
predict(dp2)

0

In [106]:
predict(dp3)

1

In [107]:
predict(dp4)

1

In [113]:
import math

def sigmoid(x):
    return 1/(1+math.exp(-x))

In [119]:
w1 = 0.30
w2 = 0
w3 = 0
w4 = 13/3412.0

def mlpredict(dp):
    return 1 if sigmoid(w1+w2*dp['maxtemp']+w3*dp['mintemp']+w4*dp['maxvibration']) > 0.7 else 0

In [13]:
mlpredict(dp4)

13.795310668229778

In [14]:
dp1 = {'partno': 100, 'maxtemp': 35, 'mintemp': 35, 'maxvibration': 12, 'asperity': 0.32}
dp2 = {'partno': 101, 'maxtemp': 46, 'mintemp': 35, 'maxvibration': 21, 'asperity': 0.34}
dp3 = {'partno': 130, 'maxtemp': 56, 'mintemp': 46, 'maxvibration': 3412, 'asperity': 12.42}
dp4 = {'partno': 131, 'maxtemp': 58, 'mintemp': 48, 'maxvibration': 3542, 'asperity': 13.43}

In [15]:
dp1

{'partno': 100,
 'maxtemp': 35,
 'mintemp': 35,
 'maxvibration': 12,
 'asperity': 0.32}

In [17]:
import numpy as np
x1 = np.array([1] + [v for k, v in dp1.items()] [1:-1])
x2 = np.array([1] + [v for k, v in dp2.items()] [1:-1])
x3 = np.array([1] + [v for k, v in dp3.items()] [1:-1])
x4 = np.array([1] + [v for k, v in dp4.items()] [1:-1])

In [18]:
x1

array([ 1, 35, 35, 12])

In [22]:
w_layer1 = np.random.rand(4)

def neuron(x):
    return sigmoid(x.dot(w_layer1))

In [23]:
neuron(x1)

0.9999989776995585

In [24]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [25]:
w_layer1 = np.random.rand(4,4)

def layer1(x):
    return sigmoid(x.dot(w_layer1))

In [26]:
x = np.array([x1,x2,x3,x4])

In [27]:
x

array([[   1,   35,   35,   12],
       [   1,   46,   35,   21],
       [   1,   56,   46, 3412],
       [   1,   58,   48, 3542]])

In [28]:
layer1(x)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
w_layer2 = np.random.rand(4,4)

def layer2(x):
    return sigmoid(x.dot(w_layer2))

In [30]:
layer2(layer1(x))

array([[0.91556707, 0.89913437, 0.86924031, 0.88277718],
       [0.91556707, 0.89913437, 0.86924031, 0.88277718],
       [0.91556707, 0.89913437, 0.86924031, 0.88277718],
       [0.91556707, 0.89913437, 0.86924031, 0.88277718]])